In [1]:
#Importing CSVs

In [3]:
import pandas as pd

In [5]:
df = pd.read_csv('parks_and_recreation.csv')
df

    employee_id    first_name     last_name   age  gender  birth_date
0             1        Leslie         Knope  44.0  Female   9/25/1979
1             3           Tom     Haverford  36.0    Male    3/4/1987
2             4         April       Ludgate  29.0  Female   3/27/1994
3             6         Donna        Meagle  46.0  Female   7/30/1977
4             7           Ann       Perkins  35.0  Female   12/1/1988
5             8         Chris       Traeger  43.0    Male  11/11/1980
6             9           Ben         Wyatt  38.0    Male   7/26/1985
7            10          Andy         Dwyer  34.0    Male   3/25/1989
8            11          Mark  Brendanawicz  40.0    Male   6/14/1983
9            12         Craig  Middlebrooks  37.0    Male   7/27/1986
10           13  Jean-Ralphio    Saperstein   NaN     NaN         NaN

In [9]:
df = pd.read_csv('parks_and_recreation.tsv',
                sep='\t')
df

    employee_id    first_name     last_name   age  gender  birth_date
0             1        Leslie         Knope  44.0  Female   9/25/1979
1             3           Tom     Haverford  36.0    Male    3/4/1987
2             4         April       Ludgate  29.0  Female   3/27/1994
3             6         Donna        Meagle  46.0  Female   7/30/1977
4             7           Ann       Perkins  35.0  Female   12/1/1988
5             8         Chris       Traeger  43.0    Male  11/11/1980
6             9           Ben         Wyatt  38.0    Male   7/26/1985
7            10          Andy         Dwyer  34.0    Male   3/25/1989
8            11          Mark  Brendanawicz  40.0    Male   6/14/1983
9            12         Craig  Middlebrooks  37.0    Male   7/27/1986
10           13  Jean-Ralphio    Saperstein   NaN     NaN         NaN

In [13]:
df = pd.read_csv('parks_and_recreation.csv', index_col='employee_id')
df

               first_name     last_name   age  gender  birth_date
employee_id
1                  Leslie         Knope  44.0  Female   9/25/1979
3                     Tom     Haverford  36.0    Male    3/4/1987
4                   April       Ludgate  29.0  Female   3/27/1994
6                   Donna        Meagle  46.0  Female   7/30/1977
7                     Ann       Perkins  35.0  Female   12/1/1988
8                   Chris       Traeger  43.0    Male  11/11/1980
9                     Ben         Wyatt  38.0    Male   7/26/1985
10                   Andy         Dwyer  34.0    Male   3/25/1989
11                   Mark  Brendanawicz  40.0    Male   6/14/1983
12                  Craig  Middlebrooks  37.0    Male   7/27/1986
13           Jean-Ralphio    Saperstein   NaN     NaN         NaN

In [15]:
df = pd.read_csv('parks_and_recreation.csv', usecols=['first_name', 'last_name'])
df

      first_name     last_name
0         Leslie         Knope
1            Tom     Haverford
2          April       Ludgate
3          Donna        Meagle
4            Ann       Perkins
5          Chris       Traeger
6            Ben         Wyatt
7           Andy         Dwyer
8           Mark  Brendanawicz
9          Craig  Middlebrooks
10  Jean-Ralphio    Saperstein

In [27]:
df = pd.read_csv('parks_and_recreation_strange_data.csv', 
                 skiprows=[0,1,2], 
                 names=['employee_id', 'first_name', 'last_name', 'age', 'gender', 'birth_date'])
df

    employee_id    first_name     last_name   age  gender  birth_date
0             1        Leslie         Knope  44.0  Female   9/25/1979
1             3           Tom     Haverford  36.0    Male    3/4/1987
2             4         April       Ludgate  29.0  Female   3/27/1994
3             6         Donna        Meagle  46.0  Female   7/30/1977
4             7           Ann       Perkins  35.0  Female   12/1/1988
5             8         Chris       Traeger  43.0    Male  11/11/1980
6             9           Ben         Wyatt  38.0    Male   7/26/1985
7            10          Andy         Dwyer  34.0    Male   3/25/1989
8            11          Mark  Brendanawicz  40.0    Male   6/14/1983
9            12         Craig  Middlebrooks  37.0    Male   7/27/1986
10           13  Jean-Ralphio    Saperstein   NaN     NaN         NaN