In [1]:
import pandas as pd

In [3]:
#Importing Different file types (JSON, text, Excel)

In [5]:
df = pd.read_json('parks_and_recreation.json')
df

    employee_id    first_name     last_name   age  gender  birth_date
0             1        Leslie         Knope  44.0  Female   9/25/1979
1             3           Tom     Haverford  36.0    Male    3/4/1987
2             4         April       Ludgate  29.0  Female   3/27/1994
3             6         Donna        Meagle  46.0  Female   7/30/1977
4             7           Ann       Perkins  35.0  Female   12/1/1988
5             8         Chris       Traeger  43.0    Male  11/11/1980
6             9           Ben         Wyatt  38.0    Male   7/26/1985
7            10          Andy         Dwyer  34.0    Male   3/25/1989
8            11          Mark  Brendanawicz  40.0    Male   6/14/1983
9            12         Craig  Middlebrooks  37.0    Male   7/27/1986
10           13  Jean-Ralphio    Saperstein   NaN    None        None

In [7]:
df = pd.read_table('parks_and_recreation.txt')
df

    employee_id    first_name     last_name   age  gender  birth_date
0             1        Leslie         Knope  44.0  Female   9/25/1979
1             3           Tom     Haverford  36.0    Male    3/4/1987
2             4         April       Ludgate  29.0  Female   3/27/1994
3             6         Donna        Meagle  46.0  Female   7/30/1977
4             7           Ann       Perkins  35.0  Female   12/1/1988
5             8         Chris       Traeger  43.0    Male  11/11/1980
6             9           Ben         Wyatt  38.0    Male   7/26/1985
7            10          Andy         Dwyer  34.0    Male   3/25/1989
8            11          Mark  Brendanawicz  40.0    Male   6/14/1983
9            12         Craig  Middlebrooks  37.0    Male   7/27/1986
10           13  Jean-Ralphio    Saperstein   NaN     NaN         NaN

In [11]:
df = pd.read_excel('parks_and_recreation.xlsx', sheet_name='demographics')
df

    employee_id    first_name     last_name   age  gender birth_date
0             1        Leslie         Knope  44.0  Female 1979-09-25
1             3           Tom     Haverford  36.0    Male 1987-03-04
2             4         April       Ludgate  29.0  Female 1994-03-27
3             6         Donna        Meagle  46.0  Female 1977-07-30
4             7           Ann       Perkins  35.0  Female 1988-12-01
5             8         Chris       Traeger  43.0    Male 1980-11-11
6             9           Ben         Wyatt  38.0    Male 1985-07-26
7            10          Andy         Dwyer  34.0    Male 1989-03-25
8            11          Mark  Brendanawicz  40.0    Male 1983-06-14
9            12         Craig  Middlebrooks  37.0    Male 1986-07-27
10           13  Jean-Ralphio    Saperstein   NaN     NaN        NaT